### ISSUE TITLE
Reduce Debris not properly working

### ISSUE THREAD

**Issue by ImStupidUser** [Metalit/Replay#51] opened 2023-01-30 18:02 UTC
Turning off "Reduce Debris" and watching/rendering the replay won't properly work. Instead you get this weird wonky mess if the saber cuts through the blocks. Would like to find a fix for this if possible.

Example: 

https://user-images.githubusercontent.com/109696506/215557418-ebe72e2e-9ea2-4575-a379-839438d52907.mp4

**Comment by Metalit** [comment] 2023-01-30 19:39
Sorry, but I don't see what's odd with the recording? It looks like the notes are being cut and then not spawning debris perfectly fine

**Comment by ImStupidUser** [comment] 2023-01-30 19:46
Oh seems like I described it pretty confusing, my bad. Is it normal for the debris to not spawn in the debris even with reduced debris turned off? Never really had this kind of "issue" if you could even call it one now.

**Comment by Metalit** [comment] 2023-01-30 20:34
Yeah, reduced debris removes the debris entirely, if that's what you mean

**Comment by ImStupidUser** [comment] 2023-01-30 21:00
Oops, said another wrong thing. The problem I'm facing atm, is that I tried to render a replay without reduced debris turned on. In the end I've got footage of the blocks being cut for a slight second but the debris delete themself right afterwards, even though reduced debris shouldn't delete them right away. Is there a way to fix this?
![Bild_2023-01-30_215101141](https://user-images.githubusercontent.com/109696506/215592067-2c78479e-434b-492c-8948-dc7edc39268a.png)

**Comment by Metalit** [comment] 2023-03-06 06:12
I've just tried this myself on 1.27 and was unable to reproduce it - the debris doesn't exist with "Reduced Debris" on, and it shows up normally with "Reduced Debris" off. I'm not sure what the issue could be on your end, but maybe it's some other mod or a weird effect with an older game version? Either way I'd like to close this, but if you still have the problem on the latest version then let me know

**Closed by Metalit** 2023-03-06 06:12 UTC

**Comment by CreeperCrafter979** [comment] 2023-04-17 22:12
Skipped testing on 1.27, but I was running into the same issue on 1.25 and still am on 1.28. Debris won't appear in replays whether the "Reduce Debris" toggle is on or off. Disabling all other non-essential mods from the BMBF mod menu didn't fix it either.
Having "Reduce Debris" on works as expected, but otherwise the white slash effect will appear for a single frame before the note and its expected debris disappear instantly.

**Comment by ImStupidUser** [comment] 2023-04-18 07:55
Also ran it on 1.28 and the issue was the same as before in 1.27.
