### ISSUE TITLE
Debris still appearing in final video, even with Reduce Debris enabled

### ISSUE THREAD

**Issue by ImStupidUser** [Metalit/Replay#59] opened 2023-04-21 22:14 UTC
The Replay mod has been acting a little weird in my experience lately after I've updated to 1.28. I've tried to render a replay which worked pretty and I've turned on reduce debris with it ,but what I've received was weird. The debris was still appearing in the final version and as mentioned in a previous Issue the debris is also [failing to spawn in replays, or is just lasting a single frame](https://github.com/Metalit/Replay/issues/51). Basically the same issue as before, but this time the reduce debris button won't even work at all. Probably something faulty on my side, but I've already re-installed beat saber multiple times now and it didn't seem to resolve the issue.

**Comment by Metalit** [comment] 2023-06-29 15:32
Looks like it was caused by beatleader replays somehow. https://github.com/BeatLeader/beatleader-qmod/commit/1d8d0776ffdbfa9cdd3a9ff641f0306039ab9b13
I'll leave this open until I see if I can do anything on my side, now that I know the cause

**Comment by Metalit** [comment] 2023-07-18 16:50
Fixed with b976d4ded2aa9a3861f33fccf7bbc07c18ed7b02 (in the next release)

**Closed by Metalit** 2023-07-18 16:50 UTC
