### ISSUE TITLE
Debris never showing up

### ISSUE THREAD

**Issue by CodeSoftGitHub** [Metalit/Replay#66] opened 2023-08-01 14:32 UTC
When I render my videos (such as https://youtu.be/-9JRwGIrE5g) debris will not show up, even though reduce debris is off.
Headset: Quest 2
Game Version: 1.28

**Comment by Metalit** [comment] 2023-08-01 17:42
Duplicate of #59 and fixed in the next update

**Closed by Metalit** 2023-08-01 17:42 UTC
