### ISSUE TITLE
Doesn't seem to work on Quest3

### ISSUE THREAD

**Issue by Duffelsalat** [Metalit/Replay#70] opened 2023-11-05 12:47 UTC
I just modded the Quest3 today, before I used the Quest2 and Version 0.2.1 of the replay mod, which worked fine.

I had the new version 0.3.1 installed on the Quest3 and it did not launch the rendering procress. It stuck at the screen that its going to render but nothing happens. I downgraded to mod version 0.2.1 on the Quest3 and rendering starts but rendering doesnt look good. Lots of flickering in it. 

Here you can see what I mean: https://www.youtube.com/watch?v=q0xiKcW0g7Y

**Comment by beaudamion** [comment] 2023-11-21 16:13
@Duffelsalat same issue. Freezes on the title / render screen... it does create temp audio and temp.mp4 files on root though. I tried to load the 0.2.1 version like you said you did but couldn't even get Beat Saber to load. Also your "flickering" issue is "shockwave" effect in beat saber. In the latest version of the mod there is a switch to turn it off in the render section. Idk if that exists for you in the older version though.

**Comment by Metalit** [comment] 2023-11-21 16:44
It's a known issue, caused by the hardware encoder's input format that I use being removed, and a fix is in the works

**Comment by The-Techy** [comment] 2023-12-15 11:46
Any idea when this might be fixed? Thanks!

**Comment by Slooshie1** [comment] 2024-01-18 05:51
Don't really want to be that guy, but could we at least get a progress/status update? This issue is several months old and still nothing. I would like to be able to render my gameplay in PC quality (and high FOV) for YouTube and this limitation really sucks...

**Comment by Slooshie1** [comment] 2024-01-23 16:18
Mod developers try not to post an ETA they can’t follow challenge (impossible)

**Closed** 2024-01-23 21:25 UTC

**Comment by The-Techy** [comment] 2024-01-23 21:43
Excited to try out the rendering again, thank you!
